apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/instance: rabbimq-discovery-challenge
      app.kubernetes.io/component: message-broker
      app.kubernetes.io/part-of: discovery-challenge
      app.kubernetes.io/managed-by: kubectl
      app.kubernetes.io/version: 0.1.0
spec:
  replicas: 1
  serviceName: rabbitmq
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/instance: rabbimq-discovery-challenge
  template:
    metadata:
      labels:
          app.kubernetes.io/name: rabbitmq
          app.kubernetes.io/instance: rabbimq-discovery-challenge
          app.kubernetes.io/component: message-broker
          app.kubernetes.io/part-of: discovery-challenge
          app.kubernetes.io/managed-by: kubectl
          app.kubernetes.io/version: 0.1.0
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.9.13-management-alpine
          ports:
            - name: amqp
              protocol: TCP
              containerPort: 5672
            - name: management
              protocol: TCP
              containerPort: 15672
            - name: epmd
              protocol: TCP
              containerPort: 4369
          volumeMounts:
            - name: config
              mountPath: /etc/rabbitmq/conf.d/100-discovery-challenge.conf
              subPath: rabbitmq.conf
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - status
            failureThreshold: 3
            periodSeconds:    60
            successThreshold: 1
            timeoutSeconds:   15
          readinessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - status
            failureThreshold: 3
            periodSeconds:    60
            successThreshold: 1
            timeoutSeconds:   15
          startupProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - status
            failureThreshold: 3
            periodSeconds:    60
            successThreshold: 1
            timeoutSeconds:   15
      volumes:
        - name: config
          configMap:
            name: rabbitmq-conf

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-conf
  labels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/instance: rabbimq-discovery-challenge
      app.kubernetes.io/component: message-broker
      app.kubernetes.io/part-of: discovery-challenge
      app.kubernetes.io/managed-by: kubectl
      app.kubernetes.io/version: 0.1.0
data:
  rabbitmq.conf: |
    consumer_timeout = 3000

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/instance: rabbimq-discovery-challenge
      app.kubernetes.io/component: message-broker
      app.kubernetes.io/part-of: discovery-challenge
      app.kubernetes.io/managed-by: kubectl
      app.kubernetes.io/version: 0.1.0
spec:
  type: ClusterIP
  selector:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/instance: rabbimq-discovery-challenge
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
      protocol: TCP
    - name: management
      port: 15672
      targetPort: management
      protocol: TCP
    - name: epmd
      port: 4369
      targetPort: epmd
      protocol: TCP