apiVersion: apps/v1
kind: Deployment
metadata:
  name: shield-service
spec:
  replicas: 15
  selector:
    matchLabels:
      app: shield
  template:
    metadata:
      labels:
        app: shield
    spec:
      containers:
      - name: shield-service
        image: achraf899/shield:v41
        env:
        - name: BROKER_CONN_STRING
          value: "amqp://guest:guest@rabbitmq:5672/"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        initContainers:
        - name: init-broker
          image: achraf899/simulation:v41
          imagePullPolicy: IfNotPresent
          env:
            - name: BROKER_CONN_STRING
              value: "amqp://guest:guest@rabbitmq:5672/"     
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shield-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shield-service
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 4
